### ISSUE TITLE
bro i am new user please guide me

### ISSUE THREAD

**Issue by alimallick** [im-hanzou/blockmesh-autobot#4]
![Screenshot 2024-11-14 184442](https://github.com/user-attachments/assets/77c13140-064e-47d0-b1ce-1e3df17da746)
bro i am new user please guide me

**Comment by im-hanzou** [comment]
same with tutorial bro, you can git clone script and cd to script directory first

**Comment by alimallick** [comment]
git clone a linls ?

**Comment by alimallick** [comment]
![Screenshot 2024-11-14 215208](https://github.com/user-attachments/assets/07ded372-6cd1-4183-86f9-d67c92a11f43)
?

**Comment by alimallick** [comment]
![Uploading Screenshot 2024-11-14 224440.png…]()

**Comment by im-hanzou** [comment]
just wait, and check your points everytime. its running if say "PING sucessful"

**Comment by alimallick** [comment]
Bro it's been almost 1 hour, not show points

**Comment by alimallick** [comment]
yes bro proxy i use i bought webshare a proxy

**Comment by im-hanzou** [comment]
It's free 10 proxy? May you can try buy at this link. static residental

> For real? I use a bot now but my points still increase. Maybe your proxy is bad, what proxy do you use? I bought it at https://www.922proxy.com/register?inviter_code=d03d4fed

**Comment by alimallick** [comment]
Ok thank you bro

**Comment by alimallick** [comment]
bro 922proxy price is high bro proxy will not be taken at low price

**Comment by im-hanzou** [comment]
yes, its residental proxy. just try one week plan with one proxy
