### ISSUE TITLE
Error failed ping

### ISSUE THREAD

**Issue by MHendriF** [im-hanzou/blockmesh-autobot#7]
I got error Client Error: Too Many Requests for url: https://app.blockmesh.xyz/api/report_uptime?email=xxxxx

**Comment by Anhairdrop** [comment]
![Screenshot 2024-11-15 141809](https://github.com/user-attachments/assets/d5667eaf-d1fc-43bb-8911-7222e59a629b)
Thank you, it worked, I edited it a bit to be able to log in to multiple accounts, thank you very much 👍

**Comment by im-hanzou** [comment]
> I got error Client Error: Too Many Requests for url: https://app.blockmesh.xyz/api/report_uptime?email=xxxxx

to much proxy, how much proxy in proxies.txt? i recommend 5 proxies

**Comment by im-hanzou** [comment]
> ![Screenshot 2024-11-15 141809](https://private-user-images.githubusercontent.com/73512523/386495190-d5667eaf-d1fc-43bb-8911-7222e59a629b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NTgwNTgsIm5iZiI6MTczMTY1Nzc1OCwicGF0aCI6Ii83MzUxMjUyMy8zODY0OTUxOTAtZDU2NjdlYWYtZDFmYy00M2JiLTg5MTEtNzIyMmU1OWE2MjliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDA4MDIzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwNmI5OTYzOTY1MmJlNzY0NzE3NWMyNTA4OWUzOGUwNTNhZDZlNDU0OTJjM2NhNjRlNWRhMWY4OGUyYmVmMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MkQ7-8Isq48qCD6Y81uQGxuRYaPvQGIxgWFZDzkBswo) Thank you, it worked, I edited it a bit to be able to log in to multiple accounts, thank you very much 👍

nice, you can pull request if you want

**Comment by stsrebel** [comment]
can you make it for without proxy bro

**Comment by im-hanzou** [comment]
> can you make it for without proxy bro

i will
