### ISSUE TITLE
Error 429 Too Many Requests.

### ISSUE THREAD

**Issue by nghia6969** [im-hanzou/blockmesh-autobot#8]
I received a error Too Many Requests when send PING request. Should I need to increase sleep time between function get_and_submit_task and send_uptime_report. I run only 1 proxy

**Comment by im-hanzou** [comment]
how many proxies do you use?

**Comment by nghia6969** [comment]
I use only 1 proxy

**Comment by im-hanzou** [comment]
thats normal, the points will increased sometime
